-- Reference data needed by every environment. Contains no licensed text:
-- role keys, calendar settings, Rosary set names and Bible book names/abbreviations (facts).
-- Idempotent: safe to run repeatedly.

insert into public.roles (key, description) values
  ('super_admin', 'Full access, including users, roles and content sources'),
  ('content_admin', 'Publishes, unpublishes and deletes content; manages sources and notifications'),
  ('editor', 'Creates and edits drafts and submits them for review'),
  ('user', 'Reader account: personal bookmarks, highlights, notes and preferences')
on conflict (key) do nothing;

insert into public.liturgical_calendars (code, parent_id, name_en, name_ta, settings)
values ('gr', null, 'General Roman Calendar', 'பொது உரோமை நாள்காட்டி', '{}'::jsonb)
on conflict (code) do nothing;

-- India: Epiphany, Ascension and Corpus Christi are celebrated on Sunday.
insert into public.liturgical_calendars (code, parent_id, name_en, name_ta, settings)
select 'in', id, 'India', 'இந்தியா',
  '{"epiphany_on_sunday": true, "ascension_on_sunday": true, "corpus_christi_on_sunday": true}'::jsonb
from public.liturgical_calendars where code = 'gr'
on conflict (code) do nothing;

-- Default weekday assignment (ISO: 1 = Monday … 7 = Sunday).
insert into public.rosary_mystery_sets (key, name_en, name_ta, weekdays, sort_order) values
  ('joyful', 'Joyful Mysteries', 'மகிழ்ச்சி மறைபொருள்கள்', '{1,6}', 1),
  ('luminous', 'Luminous Mysteries', 'ஒளி மறைபொருள்கள்', '{4}', 2),
  ('sorrowful', 'Sorrowful Mysteries', 'துயர மறைபொருள்கள்', '{2,5}', 3),
  ('glorious', 'Glorious Mysteries', 'மகிமை மறைபொருள்கள்', '{3,7}', 4)
on conflict (key) do nothing;

-- Bible books in Catholic canon order (canon_order drives canonical verse keys).
-- Reference versification (see scripts/import/bible/versification.ts): the numbering of the
-- Tamil common-language Bible and most English Bibles: Hebrew psalm numbers with titles not
-- counted as verses, Joel 3 chapters, Malachi 4 chapters. ESG and DAG hold the Greek additions
-- to Esther and Daniel. chapter_count is informational; readers use each translation's chapters.
-- Tamil names follow the common-language Tamil Bible's book titles.
insert into public.bible_books
  (code, osis_id, canon_order, testament, is_deuterocanonical, is_supplement, chapter_count, name_en, name_ta, full_name_ta, abbr_en, abbr_ta)
values
  ('GEN', 'Gen', 1, 'old', false, false, 50, 'Genesis', 'தொடக்க நூல்', 'தொடக்க நூல்', 'Gen', 'தொநூ'),
  ('EXO', 'Exod', 2, 'old', false, false, 40, 'Exodus', 'விடுதலைப் பயணம்', 'விடுதலைப் பயணம்', 'Exod', 'விப'),
  ('LEV', 'Lev', 3, 'old', false, false, 27, 'Leviticus', 'லேவியர்', 'லேவியர்', 'Lev', 'லேவி'),
  ('NUM', 'Num', 4, 'old', false, false, 36, 'Numbers', 'எண்ணிக்கை', 'எண்ணிக்கை', 'Num', 'எண்'),
  ('DEU', 'Deut', 5, 'old', false, false, 34, 'Deuteronomy', 'இணைச் சட்டம்', 'இணைச் சட்டம்', 'Deut', 'இச'),
  ('JOS', 'Josh', 6, 'old', false, false, 24, 'Joshua', 'யோசுவா', 'யோசுவா', 'Josh', 'யோசு'),
  ('JDG', 'Judg', 7, 'old', false, false, 21, 'Judges', 'நீதித் தலைவர்கள்', 'நீதித் தலைவர்கள்', 'Judg', 'நீத'),
  ('RUT', 'Ruth', 8, 'old', false, false, 4, 'Ruth', 'ரூத்து', 'ரூத்து', 'Ruth', 'ரூத்'),
  ('1SA', '1Sam', 9, 'old', false, false, 31, '1 Samuel', '1 சாமுவேல்', 'சாமுவேல் - முதல் நூல்', '1 Sam', '1 சாமு'),
  ('2SA', '2Sam', 10, 'old', false, false, 24, '2 Samuel', '2 சாமுவேல்', 'சாமுவேல் - இரண்டாம் நூல்', '2 Sam', '2 சாமு'),
  ('1KI', '1Kgs', 11, 'old', false, false, 22, '1 Kings', '1 அரசர்கள்', 'அரசர்கள் - முதல் நூல்', '1 Kgs', '1 அர'),
  ('2KI', '2Kgs', 12, 'old', false, false, 25, '2 Kings', '2 அரசர்கள்', 'அரசர்கள் - இரண்டாம் நூல்', '2 Kgs', '2 அர'),
  ('1CH', '1Chr', 13, 'old', false, false, 29, '1 Chronicles', '1 குறிப்பேடு', 'குறிப்பேடு - முதல் நூல்', '1 Chr', '1 குறி'),
  ('2CH', '2Chr', 14, 'old', false, false, 36, '2 Chronicles', '2 குறிப்பேடு', 'குறிப்பேடு - இரண்டாம் நூல்', '2 Chr', '2 குறி'),
  ('EZR', 'Ezra', 15, 'old', false, false, 10, 'Ezra', 'எஸ்ரா', 'எஸ்ரா', 'Ezra', 'எஸ்ரா'),
  ('NEH', 'Neh', 16, 'old', false, false, 13, 'Nehemiah', 'நெகேமியா', 'நெகேமியா', 'Neh', 'நெகே'),
  ('TOB', 'Tob', 17, 'old', true, false, 14, 'Tobit', 'தோபித்து', 'தோபித்து', 'Tob', 'தோபி'),
  ('JDT', 'Jdt', 18, 'old', true, false, 16, 'Judith', 'யூதித்து', 'யூதித்து', 'Jdt', 'யூதி'),
  ('EST', 'Esth', 19, 'old', false, false, 10, 'Esther', 'எஸ்தர்', 'எஸ்தர்', 'Esth', 'எஸ்'),
  ('1MA', '1Macc', 20, 'old', true, false, 16, '1 Maccabees', '1 மக்கபேயர்', 'மக்கபேயர் - முதல் நூல்', '1 Macc', '1 மக்'),
  ('2MA', '2Macc', 21, 'old', true, false, 15, '2 Maccabees', '2 மக்கபேயர்', 'மக்கபேயர் - இரண்டாம் நூல்', '2 Macc', '2 மக்'),
  ('JOB', 'Job', 22, 'old', false, false, 42, 'Job', 'யோபு', 'யோபு', 'Job', 'யோபு'),
  ('PSA', 'Ps', 23, 'old', false, false, 150, 'Psalms', 'திருப்பாடல்கள்', 'திருப்பாடல்கள்', 'Ps', 'திபா'),
  ('PRO', 'Prov', 24, 'old', false, false, 31, 'Proverbs', 'நீதிமொழிகள்', 'நீதிமொழிகள்', 'Prov', 'நீமொ'),
  ('ECC', 'Eccl', 25, 'old', false, false, 12, 'Ecclesiastes', 'சபை உரையாளர்', 'சபை உரையாளர்', 'Eccl', 'சஉ'),
  ('SNG', 'Song', 26, 'old', false, false, 8, 'Song of Songs', 'இனிமைமிகு பாடல்', 'இனிமைமிகு பாடல்', 'Song', 'இபா'),
  ('WIS', 'Wis', 27, 'old', true, false, 19, 'Wisdom', 'சாலமோனின் ஞானம்', 'சாலமோனின் ஞானம்', 'Wis', 'சாஞா'),
  ('SIR', 'Sir', 28, 'old', true, false, 51, 'Sirach', 'சீராக்', 'சீராக்கின் ஞானம்', 'Sir', 'சீஞா'),
  ('ISA', 'Isa', 29, 'old', false, false, 66, 'Isaiah', 'எசாயா', 'எசாயா', 'Isa', 'எசா'),
  ('JER', 'Jer', 30, 'old', false, false, 52, 'Jeremiah', 'எரேமியா', 'எரேமியா', 'Jer', 'எரே'),
  ('LAM', 'Lam', 31, 'old', false, false, 5, 'Lamentations', 'புலம்பல்', 'புலம்பல்', 'Lam', 'புல'),
  ('BAR', 'Bar', 32, 'old', true, false, 6, 'Baruch', 'பாரூக்கு', 'பாரூக்கு (எரேமியாவின் மடல்)', 'Bar', 'பாரூ'),
  ('EZK', 'Ezek', 33, 'old', false, false, 48, 'Ezekiel', 'எசேக்கியேல்', 'எசேக்கியேல்', 'Ezek', 'எசே'),
  ('DAN', 'Dan', 34, 'old', false, false, 14, 'Daniel', 'தானியேல்', 'தானியேல்', 'Dan', 'தானி'),
  ('HOS', 'Hos', 35, 'old', false, false, 14, 'Hosea', 'ஒசேயா', 'ஒசேயா', 'Hos', 'ஓசே'),
  ('JOL', 'Joel', 36, 'old', false, false, 3, 'Joel', 'யோவேல்', 'யோவேல்', 'Joel', 'யோவே'),
  ('AMO', 'Amos', 37, 'old', false, false, 9, 'Amos', 'ஆமோஸ்', 'ஆமோஸ்', 'Amos', 'ஆமோ'),
  ('OBA', 'Obad', 38, 'old', false, false, 1, 'Obadiah', 'ஒபதியா', 'ஒபதியா', 'Obad', 'ஒப'),
  ('JON', 'Jonah', 39, 'old', false, false, 4, 'Jonah', 'யோனா', 'யோனா', 'Jonah', 'யோனா'),
  ('MIC', 'Mic', 40, 'old', false, false, 7, 'Micah', 'மீக்கா', 'மீக்கா', 'Mic', 'மீக்'),
  ('NAM', 'Nah', 41, 'old', false, false, 3, 'Nahum', 'நாகூம்', 'நாகூம்', 'Nah', 'நாகூ'),
  ('HAB', 'Hab', 42, 'old', false, false, 3, 'Habakkuk', 'அபக்கூக்கு', 'அபக்கூக்கு', 'Hab', 'அப'),
  ('ZEP', 'Zeph', 43, 'old', false, false, 3, 'Zephaniah', 'செப்பனியா', 'செப்பனியா', 'Zeph', 'செப்'),
  ('HAG', 'Hag', 44, 'old', false, false, 2, 'Haggai', 'ஆகாய்', 'ஆகாய்', 'Hag', 'ஆகா'),
  ('ZEC', 'Zech', 45, 'old', false, false, 14, 'Zechariah', 'செக்கரியா', 'செக்கரியா', 'Zech', 'செக்'),
  ('MAL', 'Mal', 46, 'old', false, false, 4, 'Malachi', 'மலாக்கி', 'மலாக்கி', 'Mal', 'மலா'),
  ('MAT', 'Matt', 47, 'new', false, false, 28, 'Matthew', 'மத்தேயு', 'மத்தேயு நற்செய்தி', 'Matt', 'மத்'),
  ('MRK', 'Mark', 48, 'new', false, false, 16, 'Mark', 'மாற்கு', 'மாற்கு நற்செய்தி', 'Mark', 'மாற்'),
  ('LUK', 'Luke', 49, 'new', false, false, 24, 'Luke', 'லூக்கா', 'லூக்கா நற்செய்தி', 'Luke', 'லூக்'),
  ('JHN', 'John', 50, 'new', false, false, 21, 'John', 'யோவான்', 'யோவான் நற்செய்தி', 'John', 'யோவா'),
  ('ACT', 'Acts', 51, 'new', false, false, 28, 'Acts of the Apostles', 'திருத்தூதர் பணிகள்', 'திருத்தூதர் பணிகள்', 'Acts', 'திப'),
  ('ROM', 'Rom', 52, 'new', false, false, 16, 'Romans', 'உரோமையர்', 'உரோமையருக்கு எழுதிய திருமுகம்', 'Rom', 'உரோ'),
  ('1CO', '1Cor', 53, 'new', false, false, 16, '1 Corinthians', '1 கொரிந்தியர்', 'கொரிந்தியருக்கு எழுதிய முதல் திருமுகம்', '1 Cor', '1 கொரி'),
  ('2CO', '2Cor', 54, 'new', false, false, 13, '2 Corinthians', '2 கொரிந்தியர்', 'கொரிந்தியருக்கு எழுதிய இரண்டாம் திருமுகம்', '2 Cor', '2 கொரி'),
  ('GAL', 'Gal', 55, 'new', false, false, 6, 'Galatians', 'கலாத்தியர்', 'கலாத்தியருக்கு எழுதிய திருமுகம்', 'Gal', 'கலா'),
  ('EPH', 'Eph', 56, 'new', false, false, 6, 'Ephesians', 'எபேசியர்', 'எபேசியருக்கு எழுதிய திருமுகம்', 'Eph', 'எபே'),
  ('PHP', 'Phil', 57, 'new', false, false, 4, 'Philippians', 'பிலிப்பியர்', 'பிலிப்பியருக்கு எழுதிய திருமுகம்', 'Phil', 'பிலி'),
  ('COL', 'Col', 58, 'new', false, false, 4, 'Colossians', 'கொலோசையர்', 'கொலோசையருக்கு எழுதிய திருமுகம்', 'Col', 'கொலோ'),
  ('1TH', '1Thess', 59, 'new', false, false, 5, '1 Thessalonians', '1 தெசலோனிக்கர்', 'தெசலோனிக்கருக்கு எழுதிய முதல் திருமுகம்', '1 Thess', '1 தெச'),
  ('2TH', '2Thess', 60, 'new', false, false, 3, '2 Thessalonians', '2 தெசலோனிக்கர்', 'தெசலோனிக்கருக்கு எழுதிய இரண்டாம் திருமுகம்', '2 Thess', '2 தெச'),
  ('1TI', '1Tim', 61, 'new', false, false, 6, '1 Timothy', '1 திமொத்தேயு', 'திமொத்தேயுவுக்கு எழுதிய முதல் திருமுகம்', '1 Tim', '1 திமொ'),
  ('2TI', '2Tim', 62, 'new', false, false, 4, '2 Timothy', '2 திமொத்தேயு', 'திமொத்தேயுவுக்கு எழுதிய இரண்டாம் திருமுகம்', '2 Tim', '2 திமொ'),
  ('TIT', 'Titus', 63, 'new', false, false, 3, 'Titus', 'தீத்து', 'தீத்துக்கு எழுதிய திருமுகம்', 'Titus', 'தீத்'),
  ('PHM', 'Phlm', 64, 'new', false, false, 1, 'Philemon', 'பிலமோன்', 'பிலமோனுக்கு எழுதிய திருமுகம்', 'Phlm', 'பில'),
  ('HEB', 'Heb', 65, 'new', false, false, 13, 'Hebrews', 'எபிரேயர்', 'எபிரேயருக்கு எழுதிய திருமுகம்', 'Heb', 'எபி'),
  ('JAS', 'Jas', 66, 'new', false, false, 5, 'James', 'யாக்கோபு', 'யாக்கோபு எழுதிய திருமுகம்', 'Jas', 'யாக்'),
  ('1PE', '1Pet', 67, 'new', false, false, 5, '1 Peter', '1 பேதுரு', 'பேதுரு எழுதிய முதல் திருமுகம்', '1 Pet', '1 பேது'),
  ('2PE', '2Pet', 68, 'new', false, false, 3, '2 Peter', '2 பேதுரு', 'பேதுரு எழுதிய இரண்டாம் திருமுகம்', '2 Pet', '2 பேது'),
  ('1JN', '1John', 69, 'new', false, false, 5, '1 John', '1 யோவான்', 'யோவான் எழுதிய முதல் திருமுகம்', '1 John', '1 யோவா'),
  ('2JN', '2John', 70, 'new', false, false, 1, '2 John', '2 யோவான்', 'யோவான் எழுதிய இரண்டாம் திருமுகம்', '2 John', '2 யோவா'),
  ('3JN', '3John', 71, 'new', false, false, 1, '3 John', '3 யோவான்', 'யோவான் எழுதிய மூன்றாம் திருமுகம்', '3 John', '3 யோவா'),
  ('JUD', 'Jude', 72, 'new', false, false, 1, 'Jude', 'யூதா', 'யூதா எழுதிய திருமுகம்', 'Jude', 'யூதா'),
  ('REV', 'Rev', 73, 'new', false, false, 22, 'Revelation', 'திருவெளிப்பாடு', 'யோவானுக்கு அருளப்பெற்ற திருவெளிப்பாடு', 'Rev', 'திவெ'),
  ('ESG', 'EsthGr', 74, 'old', true, true, 10, 'Esther (Greek additions)', 'எஸ்தர் (கி)', 'எஸ்தர் (கிரேக்கம்)', 'Esth Gr', 'எஸ் (கி)'),
  ('DAG', 'AddDan', 75, 'old', true, true, 3, 'Daniel (Greek additions)', 'தானியேல் (இ)', 'தானியேல்: இணைப்புகள்', 'Dan Gr', 'தானி (இ)')
on conflict (code) do nothing;

insert into public.bible_book_names (book_id, language, alias)
select b.id, v.language, v.alias
from (values
  ('GEN', 'en', 'GEN'),
  ('GEN', 'en', 'Gen'),
  ('GEN', 'en', 'Genesis'),
  ('GEN', 'ta', 'ஆதியாகமம்'),
  ('GEN', 'ta', 'தொடக்க நூல்'),
  ('GEN', 'ta', 'தொநூ'),
  ('EXO', 'en', 'EXO'),
  ('EXO', 'en', 'Exod'),
  ('EXO', 'en', 'Exodus'),
  ('EXO', 'ta', 'யாத்திராகமம்'),
  ('EXO', 'ta', 'விடுதலைப் பயணம்'),
  ('EXO', 'ta', 'விப'),
  ('LEV', 'en', 'LEV'),
  ('LEV', 'en', 'Lev'),
  ('LEV', 'en', 'Leviticus'),
  ('LEV', 'ta', 'லேவி'),
  ('LEV', 'ta', 'லேவியர்'),
  ('LEV', 'ta', 'லேவிய‌ராகமம்'),
  ('NUM', 'en', 'NUM'),
  ('NUM', 'en', 'Num'),
  ('NUM', 'en', 'Numbers'),
  ('NUM', 'ta', 'எண்'),
  ('NUM', 'ta', 'எண்ணாகமம்'),
  ('NUM', 'ta', 'எண்ணிக்கை'),
  ('DEU', 'en', 'DEU'),
  ('DEU', 'en', 'Deut'),
  ('DEU', 'en', 'Deuteronomy'),
  ('DEU', 'ta', 'இச'),
  ('DEU', 'ta', 'இணைச் சட்டம்'),
  ('DEU', 'ta', 'உபாகமம்'),
  ('JOS', 'en', 'JOS'),
  ('JOS', 'en', 'Josh'),
  ('JOS', 'en', 'Joshua'),
  ('JOS', 'ta', 'யோசு'),
  ('JOS', 'ta', 'யோசுவா'),
  ('JDG', 'en', 'JDG'),
  ('JDG', 'en', 'Judg'),
  ('JDG', 'en', 'Judges'),
  ('JDG', 'ta', 'நீத'),
  ('JDG', 'ta', 'நீதித் தலைவர்கள்'),
  ('JDG', 'ta', 'நீதிபதிகள்/நியாயாதிபதிகள் ஆகமம்'),
  ('RUT', 'en', 'RUT'),
  ('RUT', 'en', 'Ruth'),
  ('RUT', 'ta', 'ரூத்'),
  ('RUT', 'ta', 'ரூத்து'),
  ('1SA', 'en', '1 Sam'),
  ('1SA', 'en', '1 Samuel'),
  ('1SA', 'en', '1SA'),
  ('1SA', 'en', '1Sam'),
  ('1SA', 'ta', '1 சாமு'),
  ('1SA', 'ta', '1 சாமுவேல்'),
  ('1SA', 'ta', 'சாமுவேல் - முதல் நூல்'),
  ('2SA', 'en', '2 Sam'),
  ('2SA', 'en', '2 Samuel'),
  ('2SA', 'en', '2SA'),
  ('2SA', 'en', '2Sam'),
  ('2SA', 'ta', '2 சாமு'),
  ('2SA', 'ta', '2 சாமுவேல்'),
  ('2SA', 'ta', 'சாமுவேல் - இரண்டாம் நூல்'),
  ('1KI', 'en', '1 Kgs'),
  ('1KI', 'en', '1 Kings'),
  ('1KI', 'en', '1KI'),
  ('1KI', 'en', '1Kgs'),
  ('1KI', 'ta', '1 அர'),
  ('1KI', 'ta', '1 அரசர்கள்'),
  ('1KI', 'ta', 'அரசர்கள் - முதல் நூல்'),
  ('1KI', 'ta', 'இராஜாக்கள் - முதல் நூல்'),
  ('2KI', 'en', '2 Kgs'),
  ('2KI', 'en', '2 Kings'),
  ('2KI', 'en', '2KI'),
  ('2KI', 'en', '2Kgs'),
  ('2KI', 'ta', '2 அர'),
  ('2KI', 'ta', '2 அரசர்கள்'),
  ('2KI', 'ta', 'அரசர்கள் - இரண்டாம் நூல்'),
  ('2KI', 'ta', 'இராஜாக்கள் - இரண்டாம் நூல்'),
  ('1CH', 'en', '1 Chr'),
  ('1CH', 'en', '1 Chronicles'),
  ('1CH', 'en', '1CH'),
  ('1CH', 'en', '1Chr'),
  ('1CH', 'ta', '1 குறி'),
  ('1CH', 'ta', '1 குறிப்பேடு'),
  ('1CH', 'ta', 'குறிப்பேடு - முதல் நூல்'),
  ('1CH', 'ta', 'நாளாகமம் - முதல் நூல்'),
  ('2CH', 'en', '2 Chr'),
  ('2CH', 'en', '2 Chronicles'),
  ('2CH', 'en', '2CH'),
  ('2CH', 'en', '2Chr'),
  ('2CH', 'ta', '2 குறி'),
  ('2CH', 'ta', '2 குறிப்பேடு'),
  ('2CH', 'ta', 'குறிப்பேடு - இரண்டாம் நூல்'),
  ('2CH', 'ta', 'நாளாகமம் - இரண்டாம் நூல்'),
  ('EZR', 'en', 'EZR'),
  ('EZR', 'en', 'Ezra'),
  ('EZR', 'ta', 'எஸ்ரா'),
  ('NEH', 'en', 'NEH'),
  ('NEH', 'en', 'Neh'),
  ('NEH', 'en', 'Nehemiah'),
  ('NEH', 'ta', 'நெகே'),
  ('NEH', 'ta', 'நெகேமியா'),
  ('TOB', 'en', 'TOB'),
  ('TOB', 'en', 'Tob'),
  ('TOB', 'en', 'Tobit'),
  ('TOB', 'ta', 'தொபியாசு ஆகமம்'),
  ('TOB', 'ta', 'தோபி'),
  ('TOB', 'ta', 'தோபித்து'),
  ('JDT', 'en', 'JDT'),
  ('JDT', 'en', 'Jdt'),
  ('JDT', 'en', 'Judith'),
  ('JDT', 'ta', 'யூதி'),
  ('JDT', 'ta', 'யூதித்து'),
  ('EST', 'en', 'EST'),
  ('EST', 'en', 'Esth'),
  ('EST', 'en', 'Esther'),
  ('EST', 'ta', 'எஸ்'),
  ('EST', 'ta', 'எஸ்தர்'),
  ('1MA', 'en', '1 Macc'),
  ('1MA', 'en', '1 Maccabees'),
  ('1MA', 'en', '1MA'),
  ('1MA', 'en', '1Macc'),
  ('1MA', 'ta', '1 மக்'),
  ('1MA', 'ta', '1 மக்கபே ஆகமம்'),
  ('1MA', 'ta', '1 மக்கபேயர்'),
  ('1MA', 'ta', 'மக்கபேயர் - முதல் நூல்'),
  ('2MA', 'en', '2 Macc'),
  ('2MA', 'en', '2 Maccabees'),
  ('2MA', 'en', '2MA'),
  ('2MA', 'en', '2Macc'),
  ('2MA', 'ta', '2 மக்'),
  ('2MA', 'ta', '2 மக்கபே ஆகமம்'),
  ('2MA', 'ta', '2 மக்கபேயர்'),
  ('2MA', 'ta', 'மக்கபேயர் - இரண்டாம் நூல்'),
  ('JOB', 'en', 'JOB'),
  ('JOB', 'en', 'Job'),
  ('JOB', 'ta', 'யோபு'),
  ('PSA', 'en', 'PSA'),
  ('PSA', 'en', 'Ps'),
  ('PSA', 'en', 'Psalms'),
  ('PSA', 'ta', 'சங்கீதங்கள்'),
  ('PSA', 'ta', 'திபா'),
  ('PSA', 'ta', 'திருப்பாடல்கள்'),
  ('PRO', 'en', 'PRO'),
  ('PRO', 'en', 'Prov'),
  ('PRO', 'en', 'Proverbs'),
  ('PRO', 'ta', 'நீதிமொழிகள்'),
  ('PRO', 'ta', 'நீமொ'),
  ('PRO', 'ta', 'பழமொழி ஆகமம்'),
  ('ECC', 'en', 'ECC'),
  ('ECC', 'en', 'Eccl'),
  ('ECC', 'en', 'Ecclesiastes'),
  ('ECC', 'ta', 'சஉ'),
  ('ECC', 'ta', 'சங்கத் திருவுரை ஆகமம்'),
  ('ECC', 'ta', 'சபை உரையாளர்'),
  ('SNG', 'en', 'SNG'),
  ('SNG', 'en', 'Song'),
  ('SNG', 'en', 'Song of Songs'),
  ('SNG', 'ta', 'இனிமைமிகு பாடல்'),
  ('SNG', 'ta', 'இபா'),
  ('SNG', 'ta', 'உன்னத சங்கீதம்/பாட்டு'),
  ('WIS', 'en', 'WIS'),
  ('WIS', 'en', 'Wis'),
  ('WIS', 'en', 'Wisdom'),
  ('WIS', 'ta', 'சாஞா'),
  ('WIS', 'ta', 'சாலமோனின் ஞானம்'),
  ('WIS', 'ta', 'ஞானாகமம்'),
  ('SIR', 'en', 'SIR'),
  ('SIR', 'en', 'Sir'),
  ('SIR', 'en', 'Sirach'),
  ('SIR', 'ta', 'சீஞா'),
  ('SIR', 'ta', 'சீராக்'),
  ('SIR', 'ta', 'சீராக் ஆகமம்'),
  ('SIR', 'ta', 'சீராக்கின் ஞானம்'),
  ('ISA', 'en', 'ISA'),
  ('ISA', 'en', 'Isa'),
  ('ISA', 'en', 'Isaiah'),
  ('ISA', 'ta', 'எசா'),
  ('ISA', 'ta', 'எசாயா'),
  ('JER', 'en', 'JER'),
  ('JER', 'en', 'Jer'),
  ('JER', 'en', 'Jeremiah'),
  ('JER', 'ta', 'எரே'),
  ('JER', 'ta', 'எரேமியா'),
  ('LAM', 'en', 'LAM'),
  ('LAM', 'en', 'Lam'),
  ('LAM', 'en', 'Lamentations'),
  ('LAM', 'ta', 'புல'),
  ('LAM', 'ta', 'புலம்பல்'),
  ('BAR', 'en', 'BAR'),
  ('BAR', 'en', 'Bar'),
  ('BAR', 'en', 'Baruch'),
  ('BAR', 'ta', 'பாரூ'),
  ('BAR', 'ta', 'பாரூக்கு'),
  ('BAR', 'ta', 'பாரூக்கு (எரேமியாவின் மடல்)'),
  ('EZK', 'en', 'EZK'),
  ('EZK', 'en', 'Ezek'),
  ('EZK', 'en', 'Ezekiel'),
  ('EZK', 'ta', 'எசே'),
  ('EZK', 'ta', 'எசேக்கியேல்'),
  ('DAN', 'en', 'DAN'),
  ('DAN', 'en', 'Dan'),
  ('DAN', 'en', 'Daniel'),
  ('DAN', 'ta', 'தானி'),
  ('DAN', 'ta', 'தானியேல்'),
  ('HOS', 'en', 'HOS'),
  ('HOS', 'en', 'Hos'),
  ('HOS', 'en', 'Hosea'),
  ('HOS', 'ta', 'ஒசேயா'),
  ('HOS', 'ta', 'ஓசே'),
  ('JOL', 'en', 'JOL'),
  ('JOL', 'en', 'Joel'),
  ('JOL', 'ta', 'யோவே'),
  ('JOL', 'ta', 'யோவேல்'),
  ('AMO', 'en', 'AMO'),
  ('AMO', 'en', 'Amos'),
  ('AMO', 'ta', 'ஆமோ'),
  ('AMO', 'ta', 'ஆமோஸ்'),
  ('OBA', 'en', 'OBA'),
  ('OBA', 'en', 'Obad'),
  ('OBA', 'en', 'Obadiah'),
  ('OBA', 'ta', 'ஒப'),
  ('OBA', 'ta', 'ஒபதியா'),
  ('JON', 'en', 'JON'),
  ('JON', 'en', 'Jonah'),
  ('JON', 'ta', 'யோனா'),
  ('MIC', 'en', 'MIC'),
  ('MIC', 'en', 'Mic'),
  ('MIC', 'en', 'Micah'),
  ('MIC', 'ta', 'மீக்'),
  ('MIC', 'ta', 'மீக்கா'),
  ('NAM', 'en', 'NAM'),
  ('NAM', 'en', 'Nah'),
  ('NAM', 'en', 'Nahum'),
  ('NAM', 'ta', 'நாகூ'),
  ('NAM', 'ta', 'நாகூம்'),
  ('HAB', 'en', 'HAB'),
  ('HAB', 'en', 'Hab'),
  ('HAB', 'en', 'Habakkuk'),
  ('HAB', 'ta', 'அப'),
  ('HAB', 'ta', 'அபக்கூக்கு'),
  ('ZEP', 'en', 'ZEP'),
  ('ZEP', 'en', 'Zeph'),
  ('ZEP', 'en', 'Zephaniah'),
  ('ZEP', 'ta', 'செப்'),
  ('ZEP', 'ta', 'செப்பனியா'),
  ('HAG', 'en', 'HAG'),
  ('HAG', 'en', 'Hag'),
  ('HAG', 'en', 'Haggai'),
  ('HAG', 'ta', 'ஆகா'),
  ('HAG', 'ta', 'ஆகாய்'),
  ('ZEC', 'en', 'ZEC'),
  ('ZEC', 'en', 'Zech'),
  ('ZEC', 'en', 'Zechariah'),
  ('ZEC', 'ta', 'செக்'),
  ('ZEC', 'ta', 'செக்கரியா'),
  ('MAL', 'en', 'MAL'),
  ('MAL', 'en', 'Mal'),
  ('MAL', 'en', 'Malachi'),
  ('MAL', 'ta', 'மலா'),
  ('MAL', 'ta', 'மலாக்கி'),
  ('MAT', 'en', 'MAT'),
  ('MAT', 'en', 'Matt'),
  ('MAT', 'en', 'Matthew'),
  ('MAT', 'ta', 'மத்'),
  ('MAT', 'ta', 'மத்தேயு'),
  ('MAT', 'ta', 'மத்தேயு நற்செய்தி'),
  ('MRK', 'en', 'MRK'),
  ('MRK', 'en', 'Mark'),
  ('MRK', 'ta', 'மாற்'),
  ('MRK', 'ta', 'மாற்கு'),
  ('MRK', 'ta', 'மாற்கு நற்செய்தி'),
  ('LUK', 'en', 'LUK'),
  ('LUK', 'en', 'Luke'),
  ('LUK', 'ta', 'லூக்'),
  ('LUK', 'ta', 'லூக்கா'),
  ('LUK', 'ta', 'லூக்கா நற்செய்தி'),
  ('JHN', 'en', 'JHN'),
  ('JHN', 'en', 'John'),
  ('JHN', 'ta', 'அருளப்பர் நற்செய்தி'),
  ('JHN', 'ta', 'யோவா'),
  ('JHN', 'ta', 'யோவான்'),
  ('JHN', 'ta', 'யோவான் நற்செய்தி'),
  ('ACT', 'en', 'ACT'),
  ('ACT', 'en', 'Acts'),
  ('ACT', 'en', 'Acts of the Apostles'),
  ('ACT', 'ta', 'அப்போஸ்தலர் பணி'),
  ('ACT', 'ta', 'திப'),
  ('ACT', 'ta', 'திருத்தூதர் பணிகள்'),
  ('ROM', 'en', 'ROM'),
  ('ROM', 'en', 'Rom'),
  ('ROM', 'en', 'Romans'),
  ('ROM', 'ta', 'உரோ'),
  ('ROM', 'ta', 'உரோமையருக்கு எழுதிய திருமுகம்'),
  ('ROM', 'ta', 'உரோமையர்'),
  ('1CO', 'en', '1 Cor'),
  ('1CO', 'en', '1 Corinthians'),
  ('1CO', 'en', '1CO'),
  ('1CO', 'en', '1Cor'),
  ('1CO', 'ta', '1 கொரி'),
  ('1CO', 'ta', '1 கொரிந்தியர்'),
  ('1CO', 'ta', 'கொரிந்தியருக்கு எழுதிய முதல் திருமுகம்'),
  ('2CO', 'en', '2 Cor'),
  ('2CO', 'en', '2 Corinthians'),
  ('2CO', 'en', '2CO'),
  ('2CO', 'en', '2Cor'),
  ('2CO', 'ta', '2 கொரி'),
  ('2CO', 'ta', '2 கொரிந்தியர்'),
  ('2CO', 'ta', 'கொரிந்தியருக்கு எழுதிய இரண்டாம் திருமுகம்'),
  ('GAL', 'en', 'GAL'),
  ('GAL', 'en', 'Gal'),
  ('GAL', 'en', 'Galatians'),
  ('GAL', 'ta', 'கலா'),
  ('GAL', 'ta', 'கலாத்தியருக்கு எழுதிய திருமுகம்'),
  ('GAL', 'ta', 'கலாத்தியர்'),
  ('EPH', 'en', 'EPH'),
  ('EPH', 'en', 'Eph'),
  ('EPH', 'en', 'Ephesians'),
  ('EPH', 'ta', 'எபே'),
  ('EPH', 'ta', 'எபேசியருக்கு எழுதிய திருமுகம்'),
  ('EPH', 'ta', 'எபேசியர்'),
  ('PHP', 'en', 'PHP'),
  ('PHP', 'en', 'Phil'),
  ('PHP', 'en', 'Philippians'),
  ('PHP', 'ta', 'பிலி'),
  ('PHP', 'ta', 'பிலிப்பியருக்கு எழுதிய திருமுகம்'),
  ('PHP', 'ta', 'பிலிப்பியர்'),
  ('COL', 'en', 'COL'),
  ('COL', 'en', 'Col'),
  ('COL', 'en', 'Colossians'),
  ('COL', 'ta', 'கொலோ'),
  ('COL', 'ta', 'கொலோசையருக்கு எழுதிய திருமுகம்'),
  ('COL', 'ta', 'கொலோசையர்'),
  ('1TH', 'en', '1 Thess'),
  ('1TH', 'en', '1 Thessalonians'),
  ('1TH', 'en', '1TH'),
  ('1TH', 'en', '1Thess'),
  ('1TH', 'ta', '1 தெச'),
  ('1TH', 'ta', '1 தெசலோனிக்கர்'),
  ('1TH', 'ta', 'தெசலோனிக்கருக்கு எழுதிய முதல் திருமுகம்'),
  ('2TH', 'en', '2 Thess'),
  ('2TH', 'en', '2 Thessalonians'),
  ('2TH', 'en', '2TH'),
  ('2TH', 'en', '2Thess'),
  ('2TH', 'ta', '2 தெச'),
  ('2TH', 'ta', '2 தெசலோனிக்கர்'),
  ('2TH', 'ta', 'தெசலோனிக்கருக்கு எழுதிய இரண்டாம் திருமுகம்'),
  ('1TI', 'en', '1 Tim'),
  ('1TI', 'en', '1 Timothy'),
  ('1TI', 'en', '1TI'),
  ('1TI', 'en', '1Tim'),
  ('1TI', 'ta', '1 திமொ'),
  ('1TI', 'ta', '1 திமொத்தேயு'),
  ('1TI', 'ta', 'திமொத்தேயுவுக்கு எழுதிய முதல் திருமுகம்'),
  ('2TI', 'en', '2 Tim'),
  ('2TI', 'en', '2 Timothy'),
  ('2TI', 'en', '2TI'),
  ('2TI', 'en', '2Tim'),
  ('2TI', 'ta', '2 திமொ'),
  ('2TI', 'ta', '2 திமொத்தேயு'),
  ('2TI', 'ta', 'திமொத்தேயுவுக்கு எழுதிய இரண்டாம் திருமுகம்'),
  ('TIT', 'en', 'TIT'),
  ('TIT', 'en', 'Titus'),
  ('TIT', 'ta', 'தீத்'),
  ('TIT', 'ta', 'தீத்து'),
  ('TIT', 'ta', 'தீத்துக்கு எழுதிய திருமுகம்'),
  ('TIT', 'ta', 'தீத்துஸ்'),
  ('PHM', 'en', 'PHM'),
  ('PHM', 'en', 'Philemon'),
  ('PHM', 'en', 'Phlm'),
  ('PHM', 'ta', 'பில'),
  ('PHM', 'ta', 'பிலமோனுக்கு எழுதிய திருமுகம்'),
  ('PHM', 'ta', 'பிலமோன்'),
  ('HEB', 'en', 'HEB'),
  ('HEB', 'en', 'Heb'),
  ('HEB', 'en', 'Hebrews'),
  ('HEB', 'ta', 'எபி'),
  ('HEB', 'ta', 'எபிரேயருக்கு எழுதிய திருமுகம்'),
  ('HEB', 'ta', 'எபிரேயர்'),
  ('JAS', 'en', 'JAS'),
  ('JAS', 'en', 'James'),
  ('JAS', 'en', 'Jas'),
  ('JAS', 'ta', 'யாகப்பர்'),
  ('JAS', 'ta', 'யாக்'),
  ('JAS', 'ta', 'யாக்கோபு'),
  ('JAS', 'ta', 'யாக்கோபு எழுதிய திருமுகம்'),
  ('1PE', 'en', '1 Pet'),
  ('1PE', 'en', '1 Peter'),
  ('1PE', 'en', '1PE'),
  ('1PE', 'en', '1Pet'),
  ('1PE', 'ta', '1 பேது'),
  ('1PE', 'ta', '1 பேதுரு'),
  ('1PE', 'ta', 'இராயப்பர் எழுதிய முதல் திருமுகம்'),
  ('1PE', 'ta', 'பேதுரு எழுதிய முதல் திருமுகம்'),
  ('2PE', 'en', '2 Pet'),
  ('2PE', 'en', '2 Peter'),
  ('2PE', 'en', '2PE'),
  ('2PE', 'en', '2Pet'),
  ('2PE', 'ta', '2 பேது'),
  ('2PE', 'ta', '2 பேதுரு'),
  ('2PE', 'ta', 'இராயப்பர் எழுதிய இரண்டாம் திருமுகம்'),
  ('2PE', 'ta', 'பேதுரு எழுதிய இரண்டாம் திருமுகம்'),
  ('1JN', 'en', '1 John'),
  ('1JN', 'en', '1JN'),
  ('1JN', 'en', '1John'),
  ('1JN', 'ta', '1 யோவா'),
  ('1JN', 'ta', '1 யோவான்'),
  ('1JN', 'ta', 'அருளப்பர் எழுதிய முதல் திருமுகம்'),
  ('1JN', 'ta', 'யோவான் எழுதிய முதல் திருமுகம்'),
  ('2JN', 'en', '2 John'),
  ('2JN', 'en', '2JN'),
  ('2JN', 'en', '2John'),
  ('2JN', 'ta', '2 யோவா'),
  ('2JN', 'ta', '2 யோவான்'),
  ('2JN', 'ta', 'அருளப்பர் எழுதிய இரண்டாம் திருமுகம்'),
  ('2JN', 'ta', 'யோவான் எழுதிய இரண்டாம் திருமுகம்'),
  ('3JN', 'en', '3 John'),
  ('3JN', 'en', '3JN'),
  ('3JN', 'en', '3John'),
  ('3JN', 'ta', '3 யோவா'),
  ('3JN', 'ta', '3 யோவான்'),
  ('3JN', 'ta', 'அருளப்பர் எழுதிய மூன்றாம் திருமுகம்'),
  ('3JN', 'ta', 'யோவான் எழுதிய மூன்றாம் திருமுகம்'),
  ('JUD', 'en', 'JUD'),
  ('JUD', 'en', 'Jude'),
  ('JUD', 'ta', 'யூதா'),
  ('JUD', 'ta', 'யூதா எழுதிய திருமுகம்'),
  ('REV', 'en', 'REV'),
  ('REV', 'en', 'Rev'),
  ('REV', 'en', 'Revelation'),
  ('REV', 'ta', 'திருவெளிப்பாடு'),
  ('REV', 'ta', 'திவெ'),
  ('REV', 'ta', 'யோவானுக்கு அருளப்பெற்ற திருவெளிப்பாடு'),
  ('ESG', 'en', 'ESG'),
  ('ESG', 'en', 'Esth Gr'),
  ('ESG', 'en', 'EsthGr'),
  ('ESG', 'en', 'Esther (Greek additions)'),
  ('ESG', 'ta', 'எஸ் (கி)'),
  ('ESG', 'ta', 'எஸ்தர் (கி)'),
  ('ESG', 'ta', 'எஸ்தர் (கிரேக்கம்)'),
  ('DAG', 'en', 'AddDan'),
  ('DAG', 'en', 'DAG'),
  ('DAG', 'en', 'Dan Gr'),
  ('DAG', 'en', 'Daniel (Greek additions)'),
  ('DAG', 'ta', 'தானி (இ)'),
  ('DAG', 'ta', 'தானியேல் (இ)'),
  ('DAG', 'ta', 'தானியேல்: இணைப்புகள்')
) as v (code, language, alias)
join public.bible_books b on b.code = v.code
on conflict (language, alias_norm) do nothing;

-- Also in migration 20261005001300 (for databases seeded before it). References typed in search: every book's own abbreviations, plus the short forms common in English
-- lectionaries and missals (Jn 3:16, Mt 5, Is 9:1, Ps 23).
insert into public.bible_book_names (book_id, language, alias)
select id, 'en', abbr_en from public.bible_books
union
select id, 'ta', abbr_ta from public.bible_books
on conflict (language, alias_norm) do nothing;

insert into public.bible_book_names (book_id, language, alias)
select b.id, 'en', a.alias
from (values
  ('GEN', 'Gn'), ('EXO', 'Ex'), ('LEV', 'Lv'), ('NUM', 'Nm'), ('DEU', 'Dt'), ('JOS', 'Jos'), ('JDG', 'Jgs'),
  ('RUT', 'Ru'), ('1SA', '1 Sm'), ('2SA', '2 Sm'), ('1KI', '1 Kgs'), ('2KI', '2 Kgs'), ('1CH', '1 Chr'),
  ('2CH', '2 Chr'), ('NEH', 'Neh'), ('TOB', 'Tb'), ('JDT', 'Jdt'), ('EST', 'Est'), ('1MA', '1 Mc'), ('2MA', '2 Mc'),
  ('PSA', 'Pss'), ('PSA', 'Psalm'), ('PRO', 'Prv'), ('ECC', 'Eccl'), ('ECC', 'Qoh'), ('SNG', 'Sg'), ('WIS', 'Ws'),
  ('SIR', 'Sir'), ('ISA', 'Is'), ('JER', 'Jer'), ('LAM', 'Lam'), ('BAR', 'Bar'), ('EZK', 'Ez'), ('DAN', 'Dn'),
  ('HOS', 'Hos'), ('JOL', 'Jl'), ('AMO', 'Am'), ('OBA', 'Ob'), ('JON', 'Jon'), ('MIC', 'Mi'), ('NAM', 'Na'),
  ('HAB', 'Hb'), ('ZEP', 'Zep'), ('HAG', 'Hg'), ('ZEC', 'Zec'), ('MAL', 'Mal'), ('MAT', 'Mt'), ('MRK', 'Mk'),
  ('LUK', 'Lk'), ('JHN', 'Jn'), ('ACT', 'Acts'), ('ROM', 'Rom'), ('1CO', '1 Cor'), ('2CO', '2 Cor'), ('GAL', 'Gal'),
  ('EPH', 'Eph'), ('PHP', 'Phil'), ('COL', 'Col'), ('1TH', '1 Thes'), ('2TH', '2 Thes'), ('1TI', '1 Tm'),
  ('2TI', '2 Tm'), ('TIT', 'Ti'), ('PHM', 'Phlm'), ('HEB', 'Heb'), ('JAS', 'Jas'), ('1PE', '1 Pt'), ('2PE', '2 Pt'),
  ('1JN', '1 Jn'), ('2JN', '2 Jn'), ('3JN', '3 Jn'), ('JUD', 'Jude'), ('REV', 'Rv')
) as a (code, alias)
join public.bible_books b on b.code = a.code
on conflict (language, alias_norm) do nothing;


-- Prayer categories (taxonomy only; prayer texts are imported, see docs/IMPORT.md).
insert into public.prayer_categories (slug, name_en, name_ta, sort_order) values
  ('essential', 'Essential prayers', 'அடிப்படைச் செபங்கள்', 1),
  ('daily', 'Daily prayers', 'அன்றாடச் செபங்கள்', 2),
  ('marian', 'Prayers to Mary', 'மரியன்னை செபங்கள்', 3),
  ('saints-angels', 'Saints and angels', 'புனிதர்களும் வானதூதர்களும்', 4),
  ('sacraments', 'Confession and Communion', 'ஒப்புரவு மற்றும் நற்கருணை', 5),
  ('departed', 'For the faithful departed', 'இறந்தோருக்காக', 6)
on conflict (slug) do nothing;
