-- Liturgy: calendars, celebrations, generated liturgical days, lectionary, reflections.
-- liturgical_days rows are generated by the calendar engine (lib/liturgy) per calendar and
-- year; admins may then override single days (is_override = true is never regenerated).

create table public.liturgical_calendars (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[a-z][a-z0-9-]*$'),           -- gr, in, in-<diocese>
  parent_id uuid references public.liturgical_calendars (id) on delete restrict,
  name_en text not null,
  name_ta text not null,
  -- Transfer rules, e.g. {"epiphany_on_sunday": true, "ascension_on_sunday": true, "corpus_christi_on_sunday": true}
  settings jsonb not null default '{}'::jsonb check (jsonb_typeof(settings) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.celebrations (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,                                              -- stable key shared with the engine
  calendar_id uuid not null references public.liturgical_calendars (id) on delete restrict,
  name_en text not null,
  name_ta text not null,
  rank text not null check (rank in ('solemnity', 'feast', 'memorial', 'optional_memorial', 'commemoration', 'weekday')),
  precedence smallint not null check (precedence between 1 and 13),      -- Table of Liturgical Days (UNLY 59), 1 = highest
  color text not null check (color in ('green', 'violet', 'white', 'red', 'rose', 'black', 'gold')),
  month smallint check (month between 1 and 12),                          -- null for movable celebrations
  day smallint check (day between 1 and 31),
  added_year smallint,
  removed_year smallint,
  saint_id uuid,                                                          -- FK added with the saints table
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((month is null) = (day is null)),
  check (removed_year is null or added_year is null or removed_year > added_year)
);

create index celebrations_fixed_date_idx on public.celebrations (calendar_id, month, day);

create table public.liturgical_days (
  id uuid primary key default gen_random_uuid(),
  calendar_id uuid not null references public.liturgical_calendars (id) on delete cascade,
  date date not null,
  season text not null check (season in ('advent', 'christmas', 'ordinary', 'lent', 'triduum', 'easter')),
  week_number smallint check (week_number between 0 and 34),
  sunday_cycle text not null check (sunday_cycle in ('A', 'B', 'C')),
  weekday_cycle text not null check (weekday_cycle in ('I', 'II')),
  psalter_week smallint check (psalter_week between 1 and 4),
  color text not null check (color in ('green', 'violet', 'white', 'red', 'rose', 'black', 'gold')),
  notes_en text,
  notes_ta text,
  is_override boolean not null default false,
  generated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (calendar_id, date)
);

create index liturgical_days_date_idx on public.liturgical_days (date);

create table public.liturgical_day_celebrations (
  day_id uuid not null references public.liturgical_days (id) on delete cascade,
  celebration_id uuid not null references public.celebrations (id) on delete restrict,
  is_primary boolean not null default false,
  sort_order smallint not null default 0,
  primary key (day_id, celebration_id)
);

create unique index liturgical_day_celebrations_one_primary_idx
  on public.liturgical_day_celebrations (day_id) where is_primary;
create index liturgical_day_celebrations_celebration_idx on public.liturgical_day_celebrations (celebration_id);

-- ---------------------------------------------------------------------------
-- Lectionary: which readings belong to which Mass (references are facts; the
-- printed lectionary text is licensed content and lives in lectionary_texts)
-- ---------------------------------------------------------------------------
create table public.lectionary_sets (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,                                              -- e.g. OW05-1Mon-I, christmas-night
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.lectionary_readings (
  id uuid primary key default gen_random_uuid(),
  set_id uuid not null references public.lectionary_sets (id) on delete cascade,
  reading_type text not null
    check (reading_type in ('first', 'psalm', 'second', 'sequence', 'acclamation', 'gospel', 'procession_gospel')),
  sequence smallint not null default 1 check (sequence > 0),             -- Easter Vigil: readings 1..n
  alt_group smallint not null default 0 check (alt_group >= 0),          -- 0 = principal, 1.. = alternatives
  is_short boolean not null default false,                                -- shorter form of the same reading
  reference_display text not null,                                        -- as printed, e.g. "Is 7:10-14; 8:10"
  rubric_en text,
  rubric_ta text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (set_id, reading_type, sequence, alt_group, is_short)
);

-- Parsed, validatable form of reference_display (one row per contiguous range).
create table public.lectionary_reading_ranges (
  id uuid primary key default gen_random_uuid(),
  reading_id uuid not null references public.lectionary_readings (id) on delete cascade,
  seq smallint not null check (seq > 0),
  book_id uuid not null references public.bible_books (id) on delete restrict,
  start_chapter smallint not null,
  start_verse smallint not null,
  start_part text not null default '',
  end_chapter smallint not null,
  end_verse smallint not null,
  end_part text not null default '',
  unique (reading_id, seq),
  check ((end_chapter, end_verse) >= (start_chapter, start_verse))
);

create index lectionary_reading_ranges_book_idx on public.lectionary_reading_ranges (book_id);

create table public.lectionary_texts (
  id uuid primary key default gen_random_uuid(),
  reading_id uuid not null references public.lectionary_readings (id) on delete cascade,
  language text not null check (language in ('ta', 'en')),
  intro text,                                                             -- "A reading from…"
  refrain text,                                                           -- psalm response / acclamation
  body text not null,
  source_id uuid not null references public.content_sources (id) on delete restrict,
  status text not null default 'draft' check (status in ('draft', 'in_review', 'published', 'archived')),
  published_at timestamptz,
  created_by uuid default auth.uid() references auth.users (id) on delete set null,
  updated_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (reading_id, language)
);

-- Masses offered on a day (e.g. Christmas: Vigil, Night, Dawn, Day) and their reading sets.
create table public.liturgical_day_masses (
  id uuid primary key default gen_random_uuid(),
  day_id uuid not null references public.liturgical_days (id) on delete cascade,
  lectionary_set_id uuid not null references public.lectionary_sets (id) on delete restrict,
  celebration_id uuid references public.celebrations (id) on delete set null,
  label_en text,
  label_ta text,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (day_id, lectionary_set_id)
);

create index liturgical_day_masses_set_idx on public.liturgical_day_masses (lectionary_set_id);

-- Reflections are keyed by date (not day row) so regenerating the calendar never loses them.
create table public.reflections (
  id uuid primary key default gen_random_uuid(),
  reflection_date date not null,
  language text not null check (language in ('ta', 'en')),
  title text not null,
  body text not null,
  author text not null,
  source_id uuid not null references public.content_sources (id) on delete restrict,
  status text not null default 'draft' check (status in ('draft', 'in_review', 'published', 'archived')),
  published_at timestamptz,
  created_by uuid default auth.uid() references auth.users (id) on delete set null,
  updated_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index reflections_date_idx on public.reflections (reflection_date, language);

-- RLS ----------------------------------------------------------------------
select private.setup_reference_table('public.liturgical_calendars');
select private.setup_reference_table('public.celebrations');
select private.setup_reference_table('public.liturgical_days');
select private.setup_reference_table('public.liturgical_day_celebrations');
select private.setup_reference_table('public.lectionary_sets');
select private.setup_reference_table('public.lectionary_readings');
select private.setup_reference_table('public.lectionary_reading_ranges');
select private.setup_reference_table('public.liturgical_day_masses');
select private.setup_content_table('public.lectionary_texts');
select private.setup_content_table('public.reflections');
